server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/e2buy
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 106.52.158.23
  rabbitmq:
    host: 127.0.0.1
    username: e2buy
    password: e2buy
    virtual-host: /e2buy
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.e2buy.user.pojo
