server:
  port: 10010
spring:
  application:
    name: e2buy-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
      #拉取服务间隔时间
    registry-fetch-interval-seconds: 5

zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
    search-service: /search/** #路由到搜索微服务
    user-service: # 为什么/user/** 没法自动指定端口
      path: /user/**
      url: http://localhost:8085/user
    auth-service:
      path: /auth/**
      url: http://localhost:8087/auth
  add-host-header: true # 携带域名信息
  sensitive-headers:  #覆盖默认敏感头信息
e2buy:
  jwt:
    pubKeyPath: C:\Users\Admini\Desktop\temp\rsa\rsa.pub # 公钥地址
    cookieName: E2BUY_TOKEN
  filter:
    allowPaths:
      - /api/auth # - 代表集合
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item